# Generated by Django 5.1.7 on 2025-04-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_reward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xp',
            field=models.IntegerField(null=True),
        ),
    ]
