# Generated by Django 4.2.19 on 2025-03-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_user_userprofile_team_reward_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='user',
        ),
        migrations.AddField(
            model_name='reward',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.task'),
        ),
    ]
