# Generated by Django 5.1.7 on 2025-04-14 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user',
            field=models.ManyToManyField(related_name='skibidi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_user',
        ),
    ]
