# Generated by Django 5.2.12 on 2026-05-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_item_useritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='base.item'),
        ),
    ]
