# Generated by Django 5.2.12 on 2026-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_reward_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
